#!/bin/bash

# get current version from package-config/ts/package.json
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PACKAGE_JSON_PATH="$REPO_ROOT/package-config/ts/package.json"
if [ ! -f "$PACKAGE_JSON_PATH" ]; then
  echo "Could not find $PACKAGE_JSON_PATH. Please make sure you are running this script from the root of the repository."
  exit 1
fi
CURRENT_VERSION=$(jq -r '.version' "$PACKAGE_JSON_PATH")

# create git tags for current version
git tag -a "v$CURRENT_VERSION" -m "gen/go/v$CURRENT_VERSION"

# push tags
git push --tags origin